// SB Sandwich Week 2026 — Restaurant Data (full)
// Loads on/after dataLiveDate. Fill menuItems from the printed menu (out June 25).
// Event: June 25–July 1, 2026
const SOURCE_URL = "https://www.independent.com/2026/06/24/santa-barbaras-sandwich-week-returns/";

const AREA_COLORS = {
  "Downtown": "#e63946",
  "Funk Zone": "#f59e0b",
  "Waterfront": "#0ea5e9",
  "The Mesa": "#16a34a",
  "Upper State": "#0891b2",
  "Eastside": "#a21caf",
  "Westside": "#db2777",
  "Noleta": "#65a30d",
  "Goleta": "#2d6a4f",
  "Isla Vista": "#7b2cbf",
  "Montecito": "#92400e",
  "Summerland": "#0d9488",
  "Carpinteria": "#1d3557",
  "Santa Ynez Valley": "#6b7280",
};

const restaurants = [
  {
    name: "Bistro Amasa",
    address: "1404 De La Vina St, Santa Barbara, CA 93101",
    area: "Downtown",
    lat: 34.423592,
    lng: -119.709243,
    mapUrl: "https://maps.app.goo.gl/MAozSBD7CEw2YWa88",
    appleMapsUrl: "https://maps.apple/p/yxJnNMQVvtIow4",
    website: "https://www.bistroamasa.com/",
    phone: "805-500-7829",
    instagram: "bistroamasa",
    menuItems: [
      { name: "Fried Chicken Sandwich", description: "Buttermilk-brined, herb-breaded fried chicken thigh with dijonnaise, kale-apple slaw, and house-made pickles on a house-baked seed bun." },
    ],
  },
  {
    name: "CAYA Restaurant and Bar",
    address: "5650 Calle Real, Goleta, CA 93117",
    area: "Goleta",
    lat: 34.44157,
    lng: -119.820872,
    mapUrl: "https://maps.app.goo.gl/hy7eoz1CqQ7Xjq9F9",
    appleMapsUrl: "https://maps.apple/p/H.v1vd~tsAimCc",
    website: "https://www.cayarestaurant.com",
    phone: "805-964-1288",
    instagram: "cayarestaurant",
    menuItems: [
      { name: "Lazy Pig", description: "Slow-roasted pulled pork on a soft brioche bun with apple-mustard coleslaw, BBQ sauce, and pickles." },
    ],
  },
  {
    name: "Corner Tap Bar & Eatery",
    address: "1905 Cliff Dr, Santa Barbara, CA 93109",
    area: "The Mesa",
    lat: 34.401264,
    lng: -119.722428,
    mapUrl: "https://www.google.com/maps/search/?api=1&query=Corner+Tap+Bar+%26+Eatery+1905+Cliff+Dr%2C+Santa+Barbara%2C+CA+93109",
    appleMapsUrl: "https://maps.apple/p/drXeRN68KTqAtp",
    website: "https://www.sbcornertap.com/",
    phone: "805-690-2739",
    instagram: "cornertapsb",
    menuItems: [
      { name: "Pulled Pork Sandwich", description: "Slow-roasted pork in chipotle BBQ sauce with fried onion strings and house ranch coleslaw on a ciabatta roll." },
    ],
  },
  {
    name: "Cristino's Bakery",
    address: "170 Aero Camino, Goleta, CA 93117",
    area: "Goleta",
    lat: 34.432364,
    lng: -119.84804,
    mapUrl: "https://www.google.com/maps/search/?api=1&query=Cristino%27s+Bakery+170+Aero+Camino%2C+Goleta%2C+CA+93117",
    appleMapsUrl: "https://maps.apple/p/cgYQF1~aIWNyNN",
    website: "https://www.cristinosbakery.com/",
    phone: "805-455-6900",
    instagram: "cristinosbakery",
    menuItems: [
      { name: "Tri-Tip Sandwich", description: "Roasted tomatoes, red onions, red peppers, pepper Jack, and whole-grain Dijon aioli on house-made ciabatta." },
    ],
  },
  {
    name: "Crushcakes & Cafe (Anacapa)",
    address: "1315 Anacapa St, Santa Barbara, CA 93101",
    area: "Downtown",
    lat: 34.425637,
    lng: -119.705214,
    mapUrl: "https://www.google.com/maps/search/?api=1&query=Crushcakes+%26+Cafe+1315+Anacapa+St%2C+Santa+Barbara%2C+CA+93101",
    appleMapsUrl: "https://maps.apple/p/i.Eat4p7EGio7b",
    website: "https://www.crushcakes.com/",
    phone: "805-963-9353",
    instagram: "crushcakescafe",
    menuItems: [
      { name: "Fried Egg I'm in Love", description: "Two runny organic fried eggs and chicken-apple-sage sausage with roasted red onions, parmesan, pesto, and aioli on grilled sourdough." },
    ],
  },
  {
    name: "Crushcakes & Cafe (Goleta)",
    address: "5392 Hollister Ave, Goleta, CA 93117",
    area: "Goleta",
    lat: 34.435346, 
    lng: -119.812297,
    mapUrl: "https://www.google.com/maps/search/?api=1&query=Crushcakes+%26+Cafe+5392+Hollister+Ave%2C+Goleta%2C+CA+93117",
    appleMapsUrl: "https://maps.apple/p/Ir9WS14tYcDv6N",
    website: "https://www.crushcakes.com/",
    phone: "805-963-9353",
    instagram: "crushcakescafe",
    menuItems: [
      { name: "Fried Egg I'm in Love", description: "Two runny organic fried eggs and chicken-apple-sage sausage with roasted red onions, parmesan, pesto, and aioli on grilled sourdough." },
    ],
  },
  {
    name: "Dutch Garden Restaurant",
    address: "4203 State St, Santa Barbara, CA 93110",
    area: "Upper State",
    lat: 34.440305,
    lng: -119.763331,
    mapUrl: "https://www.google.com/maps/search/?api=1&query=Dutch+Garden+Restaurant+4203+State+St%2C+Santa+Barbara%2C+CA+93110",
    appleMapsUrl: "https://maps.apple/p/R-~GCUUGInh6qY",
    website: "https://www.dutchgardenrestaurant.com/",
    phone: "805-453-4556",
    instagram: "dutchgardensb",
    menuItems: [
      { name: "Reuben Sandwich", description: "Pastrami, Swiss, sauerkraut, and Russian dressing on grilled rye, with signature mustard on the side." },
    ],
  },
  {
    name: "Etty's Jewish Deli & Bakery",
    address: "524 Chapala St, Santa Barbara, CA 93101",
    area: "Downtown",
    lat: 34.416639,
    lng: -119.697143,
    mapUrl: "https://www.google.com/maps/search/?api=1&query=Etty%27s+Jewish+Deli+%26+Bakery+524+Chapala+St%2C+Santa+Barbara%2C+CA+93101",
    appleMapsUrl: "https://maps.apple/p/tNRY0cWUwsfRTC",
    website: "https://www.jewishsantabarbara.org/deli/",
    phone: "805-957-1115",
    instagram: "ettysdeli",
    menuItems: [
      { name: "The Hochman Hottie Pastrami", description: "Briny, peppery, tender pastrami with Russian dressing and crunchy kraut on house-baked rye; half sandwich with a dill pickle and side." },
    ],
  },
  {
    name: "Fresco at the Market",
    address: "38 W Victoria St, Ste 102, Santa Barbara, CA 93101",
    area: "Downtown",
    lat: 34.423601,
    lng: -119.707027,
    mapUrl: "https://www.google.com/maps/search/?api=1&query=Fresco+at+the+Market+38+W+Victoria+St%2C+Ste+102%2C+Santa+Barbara%2C+CA+93101",
    appleMapsUrl: "https://maps.apple/p/2vk0daDa8-pGTx",
    website: "https://www.fresco-sb.com/",
    phone: "805-770-7994",
    instagram: "fresco_sb",
    menuItems: [
      { name: "The Grinder", description: "Green olives, pepperoncini, roasted red pepper, salami, ham, mortadella, provolone, tomatoes, red onion, and Italian dressing on a bolillo roll." },
    ],
  },
  {
    name: "Gino's Sicilian Express",
    address: "12 W Figueroa St, Santa Barbara, CA 93101",
    area: "Downtown",
    lat: 34.422147,
    lng: -119.703687,
    mapUrl: "https://www.google.com/maps/search/?api=1&query=Gino%27s+Sicilian+Express+12+W+Figueroa+St%2C+Santa+Barbara%2C+CA+93101",
    appleMapsUrl: "https://maps.apple/p/QjQ7vnIg6KLvrm",
    website: "https://www.ginospizzapies.com/",
    phone: "805-962-9442",
    instagram: null,
    menuItems: [
      { name: "Meatball Panini", description: "All-beef meatball, oozing mozzarella, and marinara baked in pizza-oven dough." },
    ],
  },
  {
    name: "Goodland Waffles and Melts",
    address: "1131 State St, Santa Barbara, CA 93101",
    area: "Downtown",
    lat: 34.423001,
    lng: -119.704381,
    mapUrl: "https://www.google.com/maps/search/?api=1&query=Goodland+Waffles+and+Melts+1131+State+St%2C+Santa+Barbara%2C+CA+93101",
    appleMapsUrl: "https://maps.apple/p/JDAsQTQIrTFcnm",
    website: "https://www.goodlandwaffles.com/",
    phone: "805-259-4356",
    instagram: "goodlandwafflesandmelts",
    menuItems: [
      { name: "The Wake & Bacon Melt", description: "Scrambled eggs, cheddar Jack, crispy bacon, scallions, and house peach-chipotle cream cheese on grilled Texas toast." },
    ],
  },
  {
    name: "Haas's Fine Ice Cream",
    address: "3987 State St, Ste B, Santa Barbara, CA 93105",
    area: "Upper State",
    lat: 34.439525,
    lng: -119.751625,
    mapUrl: "https://www.google.com/maps/search/?api=1&query=Haas%27s+Fine+Ice+Cream+3987+State+St%2C+Ste+B%2C+Santa+Barbara%2C+CA+93105",
    appleMapsUrl: "https://maps.apple/p/7kPAVN3NA9ILjI",
    website: null,
    phone: "805-793-1271",
    instagram: null,
    menuItems: [
      { name: "Ice Cream Sandwich", description: "A hefty scoop of ice cream between two warm, house-baked chocolate chip cookies; 24 flavors to choose from." },
    ],
  },
  {
    name: "Hook & Press Donuts",
    address: "15 E Figueroa St, Santa Barbara, CA 93101",
    area: "Downtown",
    lat: 34.423094,
    lng: -119.702845,
    mapUrl: "https://www.google.com/maps/search/?api=1&query=Hook+%26+Press+Donuts+15+E+Figueroa+St%2C+Santa+Barbara%2C+CA+93101",
    appleMapsUrl: "https://maps.apple/p/hVCiyL.8-fjT9R",
    website: "https://www.hookandpressdonuts.com/",
    phone: "805-869-6635",
    instagram: "hookandpressdonuts",
    menuItems: [
      { name: "The GOAT", description: "Fluffy egg and bacon on a dense buttermilk biscuit with arugula, bourbon bacon jam, whipped goat cheese, and flaky salt." },
    ],
  },
  {
    name: "I.V. Deli Mart",
    address: "6553 Pardall Rd, Isla Vista, CA 93117",
    area: "Isla Vista",
    lat: 34.412906,
    lng: -119.856403,
    mapUrl: "https://www.google.com/maps/search/?api=1&query=I.V.+Deli+Mart+6553+Pardall+Rd%2C+Isla+Vista%2C+CA+93117",
    appleMapsUrl: "https://maps.apple/p/FWJFFqzq8xKPog",
    website: "https://ivdelimart.com/",
    phone: "805-562-8858",
    instagram: "ivdelimart",
    vegetarian: true,
    glutenFree: true,
    menuItems: [
      { name: "Turkey Presto Avocado Sandwich", description: "Turkey, lettuce, tomato, onion, avocado, mayo, and pesto on a French roll." },
      { name: "Vegan Prime California Turkey Club", description: "Vegan bacon, vegan black-pepper turkey, veganaise, mustard, avocado, tomato, cucumber, bell peppers, onion, lettuce, and pepperoncini." },
    ],
  },
  {
    name: "Jonesy's Fried Chicken",
    address: "282 Orange Ave, Goleta, CA 93117",
    area: "Goleta",
    lat: 34.434138,
    lng: -119.828632,
    mapUrl: "https://www.google.com/maps/search/?api=1&query=Jonesy%27s+Fried+Chicken+282+Orange+Ave%2C+Goleta%2C+CA+93117",
    appleMapsUrl: "https://maps.apple/p/N29hUdX_BJDsDw",
    website: "https://jonesysfriedchicken.com/",
    phone: "805-571-7060",
    instagram: "jonesysfriedchicken",
    menuItems: [
      { name: "The JFC Original", description: "Crispy, tender chicken breast with zesty JFC sauce, shaved iceberg, and dill pickle on a fluffy French bun." },
    ],
  },
  {
    name: "Lighthouse Coffee (Cliff Dr)",
    address: "1819 Cliff Dr, Santa Barbara, CA 93109",
    area: "The Mesa",
    lat: 34.401054, 
    lng: -119.721558,
    mapUrl: "https://www.google.com/maps/search/?api=1&query=Lighthouse+Coffee+1819+Cliff+Dr%2C+Santa+Barbara%2C+CA+93109",
    appleMapsUrl: "https://maps.apple/p/_B5R4m.DfPDp4b",
    website: "https://www.lighthousecoffeesb.com/",
    phone: "805-679-5153",
    instagram: null,
    menuItems: [
      { name: "Breakfast Sandwich", description: "Two scrambled eggs, three strips of bacon, avocado, grated cheddar, and tomato on an English muffin with mayo and lemon pepper." },
    ],
  },
  {
    name: "Lighthouse Coffee (Chapala)",
    address: "711 Chapala St, Santa Barbara, CA 93101",
    area: "Downtown",
    lat: 34.417703, 
    lng: -119.699901,
    mapUrl: "https://www.google.com/maps/search/?api=1&query=Lighthouse+Coffee+711+Chapala+St%2C+Santa+Barbara%2C+CA+93101",
    appleMapsUrl: "https://maps.apple/p/bnsD57DGuoari4",
    website: "https://www.lighthousecoffeesb.com/",
    phone: "805-679-5153",
    instagram: null,
    menuItems: [
      { name: "Breakfast Sandwich", description: "Two scrambled eggs, three strips of bacon, avocado, grated cheddar, and tomato on an English muffin with mayo and lemon pepper." },
    ],
  },
  {
    name: "Lighthouse Coffee (E Haley)",
    address: "401 E Haley St, Santa Barbara, CA 93101",
    area: "Eastside",
    lat: 34.421400, 
    lng: -119.691171,
    mapUrl: "https://www.google.com/maps/search/?api=1&query=Lighthouse+Coffee+401+E+Haley+St%2C+Santa+Barbara%2C+CA+93101",
    appleMapsUrl: "https://maps.apple/p/-K~6RHP2Cm18yQ",
    website: "https://www.lighthousecoffeesb.com/",
    phone: "805-679-5153",
    instagram: null,
    menuItems: [
      { name: "Breakfast Sandwich", description: "Two scrambled eggs, three strips of bacon, avocado, grated cheddar, and tomato on an English muffin with mayo and lemon pepper." },
    ],
  },
  {
    name: "Lighthouse Coffee (Turnpike)",
    address: "199 S Turnpike Rd #101, Goleta, CA 93111",
    area: "Noleta",
    lat: 34.436837, 
    lng: -119.789826,
    mapUrl: "https://www.google.com/maps/search/?api=1&query=Lighthouse+Coffee+199+S+Turnpike+Rd+%23101%2C+Goleta%2C+CA+93111",
    appleMapsUrl: "https://maps.apple/p/yxZSb2gs85EE-p",
    website: "https://www.lighthousecoffeesb.com/",
    phone: "805-679-5153",
    instagram: null,
    menuItems: [
      { name: "Breakfast Sandwich", description: "Two scrambled eggs, three strips of bacon, avocado, grated cheddar, and tomato on an English muffin with mayo and lemon pepper." },
    ],
  },
  {
    name: "Lighthouse Coffee (Calle Real)",
    address: "5696 Calle Real, Goleta, CA 93117",
    area: "Goleta",
    lat: 34.441691, 
    lng: -119.824031,
    mapUrl: "https://www.google.com/maps/search/?api=1&query=Lighthouse+Coffee+5696+Calle+Real%2C+Goleta%2C+CA+93117",
    appleMapsUrl: "https://maps.apple/p/KHjJHTpFwCpXw7",
    website: "https://www.lighthousecoffeesb.com/",
    phone: "805-679-5153",
    instagram: null,
    menuItems: [
      { name: "Breakfast Sandwich", description: "Two scrambled eggs, three strips of bacon, avocado, grated cheddar, and tomato on an English muffin with mayo and lemon pepper." },
    ],
  },
  {
    name: "Mesa Burger",
    address: "315 Meigs Rd, Ste F, Santa Barbara, CA 93109",
    area: "The Mesa",
    lat: 34.400806,
    lng: -119.722701,
    mapUrl: "https://www.google.com/maps/search/?api=1&query=Mesa+Burger+315+Meigs+Rd%2C+Ste+F%2C+Santa+Barbara%2C+CA+93109",
    appleMapsUrl: "https://maps.apple/p/xNWR2B-r3FiBxf",
    website: "https://www.mesaburger.com/",
    phone: "805-963-7492",
    instagram: null,
    vegetarian: true,
    menuItems: [
      { name: "Honey Spicy BBQ Crispy Sandwich", description: "Fried chicken on a toasted brioche bun with spicy honey-garlic BBQ sauce, mustard aioli, pickles, shredded lettuce, and blue cheese; vegan version available." },
    ],
  },
  {
    name: "Mission City Sandwich Shop",
    address: "1826 Cliff Dr, Ste A, Santa Barbara, CA 93109",
    area: "The Mesa",
    lat: 34.40177,
    lng: -119.721344,
    mapUrl: "https://www.google.com/maps/search/?api=1&query=Mission+City+Sandwich+Shop+1826+Cliff+Dr%2C+Ste+A%2C+Santa+Barbara%2C+CA+93109",
    appleMapsUrl: "https://maps.apple/p/mV9afeykbL~uHJ",
    website: "https://www.missioncitysandwichshop.com/",
    phone: "805-869-2253",
    instagram: "missioncity_sandwichshop",
    menuItems: [
      { name: "My Name Is Jeff", description: "Roasted chicken, bacon, pepper Jack, Duke's mayo, street-corn relish, avocado, iceberg, and cilantro on a toasted Dutch Crunch roll with guajillo-chipotle broth." },
      { name: "The Whispers", description: "Roasted turkey, salami, Mama Lil's pepper muffuletta salad, red onion, romaine, parm-peppercorn dressing, and pesto on a toasted Dutch Crunch roll." },
    ],
  },
  {
    name: "Noe's Cafe",
    address: "129 E Anapamu St, Santa Barbara, CA 93101",
    area: "Downtown",
    lat: 34.425305,
    lng: -119.702695,
    mapUrl: "https://www.google.com/maps/search/?api=1&query=Noe%27s+Cafe+129+E+Anapamu+St%2C+Santa+Barbara%2C+CA+93101",
    appleMapsUrl: "https://maps.apple/p/Byzog8rFTN4Kt8",
    website: null,
    phone: null,
    instagram: "noescafesb",
    vegetarian: true,
    menuItems: [
      { name: "Tri-Tip", description: "Grilled onions, green chiles, lettuce, and Jack on a French roll." },
      { name: "Tuna Melt", description: "Tuna and Jack on grilled sourdough." },
      { name: "Chicken Pesto", description: "Chicken, arugula, onion, and Jack on ciabatta." },
      { name: "Chicken BLT", description: "Chicken, bacon, cheddar, and chipotle aioli on ciabatta." },
      { name: "Veggie", description: "Zucchini, bell pepper, grilled onions, avocado, Jack, and pesto on sourdough." },
    ],
  },
  {
    name: "Norton's Pastrami & Deli",
    address: "18 W Figueroa St, Santa Barbara, CA 93101",
    area: "Downtown",
    lat: 34.421999,
    lng: -119.703831,
    mapUrl: "https://www.google.com/maps/search/?api=1&query=Norton%27s+Pastrami+%26+Deli+18+W+Figueroa+St%2C+Santa+Barbara%2C+CA+93101",
    appleMapsUrl: "https://maps.apple/p/2m5Uk_~34Saba0",
    website: "https://nortonsdeli.com/",
    phone: "805-965-3210",
    instagram: null,
    menuItems: [
      { name: "\"The Best\" Hot Ham & Swiss", description: "Melted ham and Swiss with house chipotle mayo, fresh tomatoes, and house coleslaw; served with New York-style deli pickles." },
    ],
  },
  {
    name: "Panino (Santa Barbara)",
    address: "834 Santa Barbara St, Santa Barbara, CA 93101",
    area: "Downtown",
    lat: 34.422692,
    lng: -119.697992,
    mapUrl: "https://www.google.com/maps/search/?api=1&query=Panino+834+Santa+Barbara+St%2C+Santa+Barbara%2C+CA+93101",
    appleMapsUrl: "https://maps.apple/p/.AbyfjRB9KC2~a",
    website: "https://www.paninorestaurants.com",
    phone: "805-963-3700",
    instagram: null,
    vegetarian: true,
    menuItems: [
      { name: "#10 Roast Chicken", description: "Roasted chicken with sun-dried tomatoes, basil, provolone, red onion, greens, honey mustard, and mayo on your choice of bread." },
      { name: "#22 Panino Caprese", description: "Fresh mozzarella, balsamic, extra-virgin olive oil, greens, sweet tomatoes, and basil." },
    ],
  },
  {
    name: "Panino (Montecito)",
    address: "1014 Coast Village Rd, Montecito, CA 93108",
    area: "Montecito",
    lat: 34.422630, 
    lng: -119.651664,
    mapUrl: "https://www.google.com/maps/search/?api=1&query=Panino+1014+Coast+Village+Rd%2C+Montecito%2C+CA+93108",
    appleMapsUrl: "https://maps.apple/p/PEFXkVb1_iwb9K",
    website: "https://www.paninorestaurants.com",
    phone: "805-963-3700",
    instagram: null,
    vegetarian: true,
    menuItems: [
      { name: "#10 Roast Chicken", description: "Roasted chicken with sun-dried tomatoes, basil, provolone, red onion, greens, honey mustard, and mayo on your choice of bread." },
      { name: "#22 Panino Caprese", description: "Fresh mozzarella, balsamic, extra-virgin olive oil, greens, sweet tomatoes, and basil." },
    ],
  },
  {
    name: "Panino (Goleta)",
    address: "5666 Calle Real, Goleta, CA 93117",
    area: "Goleta",
    lat: 34.441603, 
    lng: -119.823092,
    mapUrl: "https://www.google.com/maps/search/?api=1&query=Panino+5666+Calle+Real%2C+Goleta%2C+CA+93117",
    appleMapsUrl: "https://maps.apple/p/K9W-Kf6xt6hnj_",
    website: "https://www.paninorestaurants.com",
    phone: "805-963-3700",
    instagram: null,
    vegetarian: true,
    menuItems: [
      { name: "#10 Roast Chicken", description: "Roasted chicken with sun-dried tomatoes, basil, provolone, red onion, greens, honey mustard, and mayo on your choice of bread." },
      { name: "#22 Panino Caprese", description: "Fresh mozzarella, balsamic, extra-virgin olive oil, greens, sweet tomatoes, and basil." },
    ],
  },
  {
    name: "Poke House",
    address: "811 State St, Ste D, Santa Barbara, CA 93101",
    area: "Downtown",
    lat: 34.419647,
    lng: -119.700116,
    mapUrl: "https://www.google.com/maps/search/?api=1&query=Poke+House+811+State+St%2C+Ste+D%2C+Santa+Barbara%2C+CA+93101",
    appleMapsUrl: "https://maps.apple/p/7E1x9a1xwzimRh",
    website: "https://www.poke.house",
    phone: "805-869-2722",
    instagram: "poke.house",
    vegetarian: true,
    menuItems: [
      { name: "Spicy Salmon Sammich", description: "Spicy miso-marinated salmon with crispy nori and sushi-rice 'bread,' mixed greens, cucumber, grape tomatoes, furikake, and sriracha aioli; tofu option available." },
    ],
  },
  {
    name: "'Que by Whiskey 'N Rye",
    address: "38 W Victoria St, Ste 108, Santa Barbara, CA 93101",
    area: "Downtown",
    lat: 34.423601,
    lng: -119.707027,
    mapUrl: "https://www.google.com/maps/search/?api=1&query=%27Que+by+Whiskey+%27N+Rye+38+W+Victoria+St%2C+Ste+108%2C+Santa+Barbara%2C+CA+93101",
    appleMapsUrl: "https://maps.apple/p/tngxQEruUBGjvC",
    website: "https://www.quesmokeshack.com",
    phone: "805-869-2193",
    instagram: "quesmokeshack",
    menuItems: [
      { name: "Carolina Pulled Pork Sando", description: "Hickory-smoked-overnight pork with crunchy dill coleslaw and pickled red onions on a soft potato bun." },
    ],
  },
  {
    name: "Rinkside Cafe",
    address: "6985 Santa Felicia Dr, Goleta, CA 93117",
    area: "Goleta",
    lat: 34.425835,
    lng: -119.871156,
    mapUrl: "https://www.google.com/maps/search/?api=1&query=Rinkside+Cafe+6985+Santa+Felicia+Dr%2C+Goleta%2C+CA+93117",
    appleMapsUrl: "https://maps.apple/p/R-0PLb8ybsZvb2",
    website: "https://www.iceinparadise.org/rinkside-cafe",
    phone: "805-335-4521",
    instagram: "rinksidecafe",
    vegetarian: true,
    menuItems: [
      { name: "Firecracker Banh Mi", description: "Toasted baguette with Szechuan-style hot-honey Firecracker Sauce, sriracha mayo, cucumber, jalapeno, scallions, pickled daikon and carrots, and fresh herbs; chicken thigh or tofu." },
    ],
  },
  {
    name: "Santa Barbara Fish Market",
    address: "7127 Hollister Ave, Ste 18, Goleta, CA 93117",
    area: "Goleta",
    lat: 34.428633, 
    lng: -119.876655,
    mapUrl: "https://www.google.com/maps/search/?api=1&query=Santa+Barbara+Fish+Market+7127+Hollister+Ave%2C+Goleta%2C+CA+93117",
    appleMapsUrl: "https://maps.apple/p/MFjhN9uKSytnZH",
    website: "https://www.sbfish.com",
    phone: "805-965-9564",
    instagram: "sbfishmarket",
    menuItems: [
      { name: "Tuna Salad Sandwich", description: "Tuna with butter lettuce, in-house cured tomatoes, Dijon aioli, dill pickles, jalapeno, green onion, Castelvetrano olives, and mayo on toasted Breadbar sourdough." },
    ],
  },
  {
    name: "Santa Barbara Pizza House",
    address: "515 State St, Santa Barbara, CA 93101",
    area: "Downtown",
    lat: 34.416992,
    lng: -119.696321,
    mapUrl: "https://www.google.com/maps/search/?api=1&query=Santa+Barbara+Pizza+House+515+State+St%2C+Santa+Barbara%2C+CA+93101",
    appleMapsUrl: "https://maps.apple/p/DWAF591VfPfy-S",
    website: "https://www.sbpizzahouse.com",
    phone: "805-637-7721",
    instagram: null,
    vegetarian: true,
    menuItems: [
      { name: "The Rincon", description: "House Nonna's meatballs in marinara with melted mozzarella and fresh basil on panunzzo pizza dough." },
      { name: "The Shoreline", description: "Chicken, mozzarella, romaine, and Caesar dressing on focaccia." },
      { name: "The Butterfly", description: "Eggplant dip, roasted red pepper, zucchini, yellow squash, mozzarella, mixed greens, and balsamic on focaccia." },
      { name: "The Refugio", description: "Pesto, salami, capicola, provolone, lettuce, tomato, and Italian dressing on focaccia." },
    ],
  },
  {
    name: "Shalhoob's (Funk Zone)",
    address: "220 Gray Ave, Santa Barbara, CA 93101",
    area: "Funk Zone",
    lat: 34.416328,
    lng: -119.690533,
    mapUrl: "https://www.google.com/maps/search/?api=1&query=Shalhoob's+220+Gray+Ave%2C+Santa+Barbara%2C+CA+93101",
    appleMapsUrl: "https://maps.apple/p/xXrzwk9r72q~I-",
    website: "https://shalhoob.com",
    phone: "805-256-7353",
    instagram: "shalhoobmeatco",
    menuItems: [
      { name: "Fried Chicken Sandwich", description: "Hand-battered fried chicken breast with honey-poppyseed slaw, bread-and-butter pickles, jalapenos, and hot honey on a brioche bun." },
    ],
  },
  {
    name: "Shalhoob's (Goleta)",
    address: "5112 Hollister Ave, Goleta, CA 93117",
    area: "Goleta",
    lat: 34.435304, 
    lng: -119.802869,
    mapUrl: "https://www.google.com/maps/search/?api=1&query=Shalhoob's+5112+Hollister+Ave%2C+Goleta%2C+CA+93117",
    appleMapsUrl: "https://maps.apple/p/0b-Z3yLt-pt29a",
    website: "https://shalhoob.com",
    phone: "805-256-7353",
    instagram: "shalhoobmeatco",
    menuItems: [
      { name: "Fried Chicken Sandwich", description: "Hand-battered fried chicken breast with honey-poppyseed slaw, bread-and-butter pickles, jalapenos, and hot honey on a brioche bun." },
    ],
  },
  {
    name: "South Coast Deli (Carrillo)",
    address: "10 E Carrillo St, Santa Barbara, CA 93101",
    area: "Downtown",
    lat: 34.421728,
    lng: -119.701382,
    mapUrl: "https://www.google.com/maps/search/?api=1&query=South+Coast+Deli+10+E+Carrillo+St%2C+Santa+Barbara%2C+CA+93101",
    appleMapsUrl: "https://maps.apple/p/VqaiokaG1RZa4~",
    website: "https://southcoastdeli.com/",
    phone: "805-845-4600",
    instagram: null,
    menuItems: [
      { name: "The Summer Abroad", description: "House-roasted pork loin with artichoke and roasted-garlic crema, mayo, marinated peppers and onions, kale in garlic dressing, and Pecorino." },
    ],
  },
  {
    name: "South Coast Deli (Patterson)",
    address: "185 S Patterson Ave, Santa Barbara, CA 93111",
    area: "Goleta",
    lat: 34.435606, 
    lng: -119.809751,
    mapUrl: "https://www.google.com/maps/search/?api=1&query=South+Coast+Deli+185+S+Patterson+Ave%2C+Santa+Barbara%2C+CA+93111",
    appleMapsUrl: "https://maps.apple/p/u55tqK1AWyIArp",
    website: "https://southcoastdeli.com/",
    phone: "805-845-4600",
    instagram: null,
    menuItems: [
      { name: "The Summer Abroad", description: "House-roasted pork loin with artichoke and roasted-garlic crema, mayo, marinated peppers and onions, kale in garlic dressing, and Pecorino." },
    ],
  },
  {
    name: "South Coast Deli (State St)",
    address: "3534 State St, Santa Barbara, CA 93105",
    area: "Upper State",
    lat: 34.440637, 
    lng: -119.739680,
    mapUrl: "https://www.google.com/maps/search/?api=1&query=South+Coast+Deli+3534+State+St%2C+Santa+Barbara%2C+CA+93105",
    appleMapsUrl: "https://maps.apple/p/Jp_1..Ri6xGxfI",
    website: "https://southcoastdeli.com/",
    phone: "805-845-4600",
    instagram: null,
    menuItems: [
      { name: "The Summer Abroad", description: "House-roasted pork loin with artichoke and roasted-garlic crema, mayo, marinated peppers and onions, kale in garlic dressing, and Pecorino." },
    ],
  },
  {
    name: "South Coast Deli (Santa Barbara St)",
    address: "205 Santa Barbara St, Santa Barbara, CA 93101",
    area: "Eastside",
    lat: 34.416097, 
    lng: -119.689893,
    mapUrl: "https://www.google.com/maps/search/?api=1&query=South+Coast+Deli+205+Santa+Barbara+St%2C+Santa+Barbara%2C+CA+93101",
    appleMapsUrl: "https://maps.apple/p/jBBUKwWAdnsmvD",
    website: "https://southcoastdeli.com/",
    phone: "805-845-4600",
    instagram: null,
    menuItems: [
      { name: "The Summer Abroad", description: "House-roasted pork loin with artichoke and roasted-garlic crema, mayo, marinated peppers and onions, kale in garlic dressing, and Pecorino." },
    ],
  },
  {
    name: "The Blue Owl",
    address: "5 W Canon Perdido St, Santa Barbara, CA 93101",
    area: "Downtown",
    lat: 34.420052,
    lng: -119.7009,
    mapUrl: "https://www.google.com/maps/search/?api=1&query=The+Blue+Owl+5+W+Canon+Perdido+St%2C+Santa+Barbara%2C+CA+93101",
    appleMapsUrl: "https://maps.apple/p/m7Vu1PFX.BrNBX",
    website: "https://theblueowlsb.com/",
    phone: "805-705-0991",
    instagram: "blueowlsb",
    vegetarian: true,
    glutenFree: true,
    menuItems: [
      { name: "Banh Mi Sandwich", description: "Toasted D'Angelo Bakery baguette with oyster-chili mayo, shredded cabbage, pickled daikon and carrots, greens, cilantro, green onions, and chili sauce; pork, chicken, beef, tofu, or eggplant, with vegan and gluten-free options." },
    ],
  },
  {
    name: "The Natural Cafe (Hitchcock)",
    address: "361 Hitchcock Way, Santa Barbara, CA 93105",
    area: "Upper State",
    lat: 34.434947,
    lng: -119.745965,
    mapUrl: "https://www.google.com/maps/search/?api=1&query=The+Natural+Cafe+361+Hitchcock+Way%2C+Santa+Barbara%2C+CA+93105",
    appleMapsUrl: "https://maps.apple/p/HTIJBf3AhaXsRj",
    website: "https://thenaturalcafe.com/",
    phone: "805-563-1163",
    instagram: null,
    vegetarian: true,
    menuItems: [
      { name: "Portobello Sandwich", description: "Marinated, thinly sliced portobello with melted Jack, grilled onions, tomato, sprouts, pesto, and garlic mayo on nine-grain bread." },
    ],
  },
  {
    name: "The Natural Cafe (Goleta)",
    address: "6990 Marketplace Dr, Goleta, CA 93117",
    area: "Goleta",
    lat: 34.429465, 
    lng: -119.871290,
    mapUrl: "https://www.google.com/maps/search/?api=1&query=The+Natural+Cafe+6990+Marketplace+Dr%2C+Goleta%2C+CA+93117",
    appleMapsUrl: "https://maps.apple/p/ziZArrr7M8KJbq",
    website: "https://thenaturalcafe.com/",
    phone: "805-563-1163",
    instagram: null,
    vegetarian: true,
    menuItems: [
      { name: "Portobello Sandwich", description: "Marinated, thinly sliced portobello with melted Jack, grilled onions, tomato, sprouts, pesto, and garlic mayo on nine-grain bread." },
    ],
  },
  {
    name: "The Patio Cafe",
    address: "3007 De La Vina St, Santa Barbara, CA 93105",
    area: "Upper State",
    lat: 34.438691,
    lng: -119.728472,
    mapUrl: "https://www.google.com/maps/search/?api=1&query=The+Patio+Cafe+3007+De+La+Vina+St%2C+Santa+Barbara%2C+CA+93105",
    appleMapsUrl: "https://maps.apple/p/u90nqscWyxCNj4",
    website: "https://www.thepatiocafesb.com/",
    phone: "805-687-3663",
    instagram: "the.patiocafesb",
    menuItems: [
      { name: "Chicken Wrapped Nugget", description: "Sriracha-tossed chicken nuggets with guac, grilled onions, lettuce, and tomato in a flour tortilla." },
      { name: "The Torta", description: "Louisiana sausage with pico de gallo, queso fresco, and sour cream, served open-faced." },
    ],
  },
  {
    name: "Valentino's Take N' Bake Pizza",
    address: "4421 Hollister Ave, Santa Barbara, CA 93110",
    area: "Noleta",
    lat: 34.439748,
    lng: -119.770609,
    mapUrl: "https://www.google.com/maps/search/?api=1&query=Valentino%27s+Take+N%27+Bake+Pizza+4421+Hollister+Ave%2C+Santa+Barbara%2C+CA+93110",
    appleMapsUrl: "https://maps.apple/p/KNEbSsp54gkWHP",
    website: null,
    phone: "805-967-7338",
    instagram: "valentinos_sb",
    vegetarian: true,
    menuItems: [
      { name: "The Tyler", description: "Diced chicken breast, crispy bacon, jalapenos, mozzarella, parmesan, ranch, avocado, and lettuce on a soft French roll." },
      { name: "Veggie Sub", description: "Tomato, onion, pickle, cucumber, zucchini, mushrooms, black olives, lettuce, provolone, mozzarella, and marinated red onions with Italian vinaigrette, mayo, and mustard." },
      { name: "Italian Sub", description: "Provolone, mozzarella, capicola ham, cotto and dry salami, tomatoes, onions, lettuce, pepperoncini, and Italian dressing." },
    ],
  },
  {
    name: "Validation Ale (Yanonali)",
    address: "102 E Yanonali St, Santa Barbara, CA 93101",
    area: "Funk Zone",
    lat: 34.415026,
    lng: -119.690101,
    mapUrl: "https://www.google.com/maps/search/?api=1&query=Validation+Ale+102+E+Yanonali+St%2C+Santa+Barbara%2C+CA+93101",
    appleMapsUrl: "https://maps.apple/p/GogauyHgiL2MGN",
    website: "https://www.validationale.com/",
    phone: "805-500-3111",
    instagram: "validationsb",
    menuItems: [
      { name: "Gochujang Fried Chicken", description: "Fried chicken in tangy gochujang sauce with crisp coleslaw, brined pickles, and cilantro on a brioche bun." },
    ],
  },
  {
    name: "Validation Ale (De La Vina)",
    address: "2840 De La Vina St, Santa Barbara, CA 93105",
    area: "Upper State",
    lat: 34.437506, 
    lng: -119.726482,
    mapUrl: "https://www.google.com/maps/search/?api=1&query=Validation+Ale+2840+De+La+Vina+St%2C+Santa+Barbara%2C+CA+93105",
    appleMapsUrl: "https://maps.apple/p/B933gW.aJ3bn4r",
    website: "https://www.validationale.com/",
    phone: "805-500-3111",
    instagram: "validationsb",
    menuItems: [
      { name: "Gochujang Fried Chicken", description: "Fried chicken in tangy gochujang sauce with crisp coleslaw, brined pickles, and cilantro on a brioche bun." },
    ],
  },
  {
    name: "Yellow Belly",
    address: "2611 De La Vina St, Santa Barbara, CA 93105",
    area: "Upper State",
    lat: 34.434846,
    lng: -119.724707,
    mapUrl: "https://www.google.com/maps/search/?api=1&query=Yellow+Belly+2611+De+La+Vina+St%2C+Santa+Barbara%2C+CA+93105",
    appleMapsUrl: "https://maps.apple/p/ppGNs1dYmHyxJ2",
    website: "https://www.yellowbellytap.com/",
    phone: "805-770-5694",
    instagram: null,
    menuItems: [
      { name: "Chipotle Chicken Tinga Sammie", description: "Slow-cooked chicken tinga on a toasted brioche bun with iceberg, avocado, pico de gallo, and cotija." },
    ],
  },
  {
    name: "Dave's Drip House",
    address: "199 S Turnpike Rd, Ste 104, Santa Barbara, CA 93111",
    area: "Noleta",
    lat: 34.436845, 
    lng: -119.789788,
    mapUrl: "https://maps.app.goo.gl/JDRM44nSK4kgjgQk6",
    appleMapsUrl: "https://maps.apple/p/o.JVvmeVW3PjqV",
    website: "https://www.davesdriphouse.com",
    phone: "805-869-2128",
    instagram: null,
    menuItems: [
      { name: "Mac Crack Sandwich", description: "Fried chicken tender (mild to inferno spice levels) on a split brioche bun with mac 'n' cheese and house pink sauce." },
      { name: "Chipotle Chicken Sandwich", description: "Deep-fried chicken strip with melted Jack, bacon, jalapenos, and chipotle aioli on grilled sourdough." },
    ],
  },
];
