// SB Sandwich Week 2026 — Restaurant Data (skeleton)
// Loads before dataLiveDate. menuItems are empty until the menu is published.
// Event: June 25–July 1, 2026
const SOURCE_URL = "https://www.independent.com/2026/06/11/sandwich-week-2026/";

const AREA_COLORS = {
  "Downtown": "#e63946",
  "Funk Zone": "#f59e0b",
  "Waterfront": "#0ea5e9",
  "The Mesa": "#16a34a",
  "Upper State": "#0891b2",
  "Eastside": "#a21caf",
  "Westside": "#db2777",
  "Noleta": "#65a30d",
  "Goleta": "#2d6a4f",
  "Isla Vista": "#7b2cbf",
  "Montecito": "#92400e",
  "Summerland": "#0d9488",
  "Carpinteria": "#1d3557",
  "Santa Ynez Valley": "#6b7280",
};

// Multi-location businesses — one flagship entry each below. Split into
// separate entries once the June 25 menu confirms which locations participate:
//   Crushcakes & Cafe — also Goleta (5392 Hollister Ave)
//   Lighthouse Coffee — also Goleta (5696 Calle Real) and (199 S Turnpike Rd)
//   Panino — also Montecito, Goleta, Los Olivos, Solvang, Santa Ynez
//   South Coast Deli — also San Roque (3534 State St), Funk Zone (205 Santa Barbara St), Goleta (185 S Patterson Ave)
//   The Natural Cafe — also Goleta (6990 Market Place Dr)
//   Validation Ale — also Uptown Annex (2840 De La Vina St, Ste C)
//
// Java's Drip House shares Dave's Dogs' Turnpike Rd location (same business).

const restaurants = [
  {
    name: "Bistro Amasa",
    address: "1404 De La Vina St, Santa Barbara, CA 93101",
    area: "Downtown",
    lat: 34.4256,
    lng: -119.7095,
    mapUrl: "https://www.google.com/maps/search/?api=1&query=Bistro+Amasa+1404+De+La+Vina+St%2C+Santa+Barbara%2C+CA+93101",
    appleMapsUrl: null,
    website: "https://www.bistroamasa.com/",
    phone: "805-500-7829",
    instagram: "bistroamasa",
    menuItems: [],
  },
  {
    name: "CAYA Restaurant and Bar",
    address: "5650 Calle Real, Goleta, CA 93117",
    area: "Goleta",
    lat: 34.4364,
    lng: -119.8276,
    mapUrl: "https://www.google.com/maps/search/?api=1&query=CAYA+Restaurant+and+Bar+5650+Calle+Real%2C+Goleta%2C+CA+93117",
    appleMapsUrl: null,
    website: "https://www.cayarestaurant.com",
    phone: "805-964-1288",
    instagram: "cayarestaurant",
    menuItems: [],
  },
  {
    name: "Corner Tap Bar & Eatery",
    address: "1905 Cliff Dr, Santa Barbara, CA 93109",
    area: "The Mesa",
    lat: 34.4015,
    lng: -119.7165,
    mapUrl: "https://www.google.com/maps/search/?api=1&query=Corner+Tap+Bar+%26+Eatery+1905+Cliff+Dr%2C+Santa+Barbara%2C+CA+93109",
    appleMapsUrl: null,
    website: "https://www.sbcornertap.com/",
    phone: "805-690-2739",
    instagram: "cornertapsb",
    menuItems: [],
  },
  {
    name: "Cristino's Bakery",
    address: "170 Aero Camino, Goleta, CA 93117",
    area: "Goleta",
    lat: 34.4337,
    lng: -119.8612,
    mapUrl: "https://www.google.com/maps/search/?api=1&query=Cristino%27s+Bakery+170+Aero+Camino%2C+Goleta%2C+CA+93117",
    appleMapsUrl: null,
    website: "https://www.cristinosbakery.com/",
    phone: "805-455-6900",
    instagram: "cristinosbakery",
    menuItems: [],
  },
  {
    name: "Crushcakes & Cafe",
    address: "1315 Anacapa St, Santa Barbara, CA 93101",
    otherLocations: [
      "5392 Hollister Ave, Goleta",
    ],
    area: "Downtown",
    lat: 34.4225,
    lng: -119.7035,
    mapUrl: "https://www.google.com/maps/search/?api=1&query=Crushcakes+%26+Cafe+1315+Anacapa+St%2C+Santa+Barbara%2C+CA+93101",
    appleMapsUrl: null,
    website: "https://www.crushcakes.com/",
    phone: "805-963-9353",
    instagram: "crushcakescafe",
    menuItems: [],
  },
  {
    name: "Dave's Dogs Grill",
    address: "149 S Turnpike Rd, Santa Barbara, CA 93111",
    area: "Noleta",
    lat: 34.4366,
    lng: -119.7965,
    mapUrl: "https://www.google.com/maps/search/?api=1&query=Dave%27s+Dogs+Grill+149+S+Turnpike+Rd%2C+Santa+Barbara%2C+CA+93111",
    appleMapsUrl: null,
    website: "https://davesdogs805.com",
    phone: "805-770-7772",
    instagram: "davesdogs805",
    menuItems: [],
  },
  {
    name: "Jake's Drip House",
    address: "199 S Turnpike Rd, Ste 104, Santa Barbara, CA 93111",
    area: "Noleta",
    lat: 34.436837,
    lng: -119.789826,
    mapUrl: "https://www.google.com/maps/search/?api=1&query=Jake%27s+Drip+House+199+S+Turnpike+Rd%2C+Santa+Barbara%2C+CA+93111",
    appleMapsUrl: null,
    website: null,
    phone: null,
    instagram: null,
    menuItems: [],
  },
  {
    name: "Dutch Garden Restaurant",
    address: "4203 State St, Santa Barbara, CA 93110",
    area: "Upper State",
    lat: 34.4403,
    lng: -119.7633,
    mapUrl: "https://www.google.com/maps/search/?api=1&query=Dutch+Garden+Restaurant+4203+State+St%2C+Santa+Barbara%2C+CA+93110",
    appleMapsUrl: null,
    website: "https://www.dutchgardenrestaurant.com/",
    phone: "805-453-4556",
    instagram: "dutchgardensb",
    menuItems: [],
  },
  {
    name: "Etty's Jewish Deli & Bakery",
    address: "524 Chapala St, Santa Barbara, CA 93101",
    area: "Downtown",
    lat: 34.4192,
    lng: -119.7016,
    mapUrl: "https://www.google.com/maps/search/?api=1&query=Etty%27s+Jewish+Deli+%26+Bakery+524+Chapala+St%2C+Santa+Barbara%2C+CA+93101",
    appleMapsUrl: null,
    website: "https://www.jewishsantabarbara.org/deli/",
    phone: "805-957-1115",
    instagram: "ettysdeli",
    menuItems: [],
  },
  {
    name: "Fresco at the Market",
    address: "38 W Victoria St, Ste 102, Santa Barbara, CA 93101",
    area: "Downtown",
    lat: 34.4225,
    lng: -119.7042,
    mapUrl: "https://www.google.com/maps/search/?api=1&query=Fresco+at+the+Market+38+W+Victoria+St%2C+Ste+102%2C+Santa+Barbara%2C+CA+93101",
    appleMapsUrl: null,
    website: "https://www.fresco-sb.com/",
    phone: "805-770-7994",
    instagram: "fresco_sb",
    menuItems: [],
  },
  {
    name: "Gino's Sicilian Express",
    address: "12 W Figueroa St, Santa Barbara, CA 93101",
    area: "Downtown",
    lat: 34.4198,
    lng: -119.7008,
    mapUrl: "https://www.google.com/maps/search/?api=1&query=Gino%27s+Sicilian+Express+12+W+Figueroa+St%2C+Santa+Barbara%2C+CA+93101",
    appleMapsUrl: null,
    website: "https://www.ginospizzapies.com/",
    phone: "805-962-9442",
    instagram: null,
    menuItems: [],
  },
  {
    name: "Goodland Waffles and Melts",
    address: "1131 State St, Santa Barbara, CA 93101",
    area: "Downtown",
    lat: 34.4221,
    lng: -119.7064,
    mapUrl: "https://www.google.com/maps/search/?api=1&query=Goodland+Waffles+and+Melts+1131+State+St%2C+Santa+Barbara%2C+CA+93101",
    appleMapsUrl: null,
    website: "https://www.goodlandwaffles.com/",
    phone: "805-259-4356",
    instagram: "goodlandwafflesandmelts",
    menuItems: [],
  },
  {
    name: "Haas's Fine Ice Cream",
    address: "3987 State St, Ste B, Santa Barbara, CA 93105",
    area: "Upper State",
    lat: 34.4413,
    lng: -119.7639,
    mapUrl: "https://www.google.com/maps/search/?api=1&query=Haas%27s+Fine+Ice+Cream+3987+State+St%2C+Ste+B%2C+Santa+Barbara%2C+CA+93105",
    appleMapsUrl: null,
    website: null,
    phone: "805-793-1271",
    instagram: null,
    menuItems: [],
  },
  {
    name: "Hook & Press Donuts",
    address: "15 E Figueroa St, Santa Barbara, CA 93101",
    area: "Downtown",
    lat: 34.42,
    lng: -119.7005,
    mapUrl: "https://www.google.com/maps/search/?api=1&query=Hook+%26+Press+Donuts+15+E+Figueroa+St%2C+Santa+Barbara%2C+CA+93101",
    appleMapsUrl: null,
    website: "https://www.hookandpressdonuts.com/",
    phone: "805-869-6635",
    instagram: "hookandpressdonuts",
    menuItems: [],
  },
  {
    name: "I.V. Deli Mart",
    address: "6553 Pardall Rd, Isla Vista, CA 93117",
    area: "Isla Vista",
    lat: 34.4127,
    lng: -119.8556,
    mapUrl: "https://www.google.com/maps/search/?api=1&query=I.V.+Deli+Mart+6553+Pardall+Rd%2C+Isla+Vista%2C+CA+93117",
    appleMapsUrl: null,
    website: "https://ivdelimart.com/",
    phone: "805-562-8858",
    instagram: "ivdelimart",
    menuItems: [],
  },
  {
    name: "Jonesy's Fried Chicken",
    address: "282 Orange Ave, Goleta, CA 93117",
    area: "Goleta",
    lat: 34.4399,
    lng: -119.829,
    mapUrl: "https://www.google.com/maps/search/?api=1&query=Jonesy%27s+Fried+Chicken+282+Orange+Ave%2C+Goleta%2C+CA+93117",
    appleMapsUrl: null,
    website: "https://jonesysfriedchicken.com/",
    phone: "805-571-7060",
    instagram: "jonesysfriedchicken",
    menuItems: [],
  },
  {
    name: "Lighthouse Coffee",
    address: "1819 Cliff Dr, Santa Barbara, CA 93109",
    otherLocations: [
      "711 Chapala St, Santa Barbara",
      "401 E Haley St, Santa Barbara",
      "199 S Turnpike Rd #101, Goleta",
      "5696 Calle Real, Goleta",
    ],
    area: "The Mesa",
    lat: 34.4015,
    lng: -119.7165,
    mapUrl: "https://www.google.com/maps/search/?api=1&query=Lighthouse+Coffee+1819+Cliff+Dr%2C+Santa+Barbara%2C+CA+93109",
    appleMapsUrl: null,
    website: "https://www.lighthousecoffeesb.com/",
    phone: null,
    instagram: null,
    menuItems: [],
  },
  {
    name: "Mesa Burger",
    address: "315 Meigs Rd, Ste F, Santa Barbara, CA 93109",
    area: "The Mesa",
    lat: 34.403,
    lng: -119.7185,
    mapUrl: "https://www.google.com/maps/search/?api=1&query=Mesa+Burger+315+Meigs+Rd%2C+Ste+F%2C+Santa+Barbara%2C+CA+93109",
    appleMapsUrl: null,
    website: "https://www.mesaburger.com/",
    phone: "805-963-7492",
    instagram: null,
    menuItems: [],
  },
  {
    name: "Mission City Sandwich Shop",
    address: "1826 Cliff Dr, Ste A, Santa Barbara, CA 93109",
    area: "The Mesa",
    lat: 34.4014,
    lng: -119.717,
    mapUrl: "https://www.google.com/maps/search/?api=1&query=Mission+City+Sandwich+Shop+1826+Cliff+Dr%2C+Ste+A%2C+Santa+Barbara%2C+CA+93109",
    appleMapsUrl: null,
    website: "https://www.missioncitysandwichshop.com/",
    phone: "805-869-2253",
    instagram: "missioncity_sandwichshop",
    menuItems: [],
  },
  {
    name: "Noe's Cafe",
    address: "129 E Anapamu St, Santa Barbara, CA 93101",
    area: "Downtown",
    lat: 34.4233,
    lng: -119.7027,
    mapUrl: "https://www.google.com/maps/search/?api=1&query=Noe%27s+Cafe+129+E+Anapamu+St%2C+Santa+Barbara%2C+CA+93101",
    appleMapsUrl: null,
    website: null,
    phone: null,
    instagram: "noescafesb",
    menuItems: [],
  },
  {
    name: "Norton's Pastrami & Deli",
    address: "18 W Figueroa St, Santa Barbara, CA 93101",
    area: "Downtown",
    lat: 34.4193,
    lng: -119.7008,
    mapUrl: "https://www.google.com/maps/search/?api=1&query=Norton%27s+Pastrami+%26+Deli+18+W+Figueroa+St%2C+Santa+Barbara%2C+CA+93101",
    appleMapsUrl: null,
    website: "https://nortonsdeli.com/",
    phone: "805-965-3210",
    instagram: null,
    menuItems: [],
  },
  {
    name: "Panino",
    address: "834 Santa Barbara St, Santa Barbara, CA 93101",
    otherLocations: [
      "1014 Coast Village Rd, Montecito",
      "5666 Calle Real, Goleta",
      "3569 Sagunto St, Santa Ynez",
      "2900 Grand Ave, Los Olivos",
      "475 First St, Solvang",
    ],
    area: "Downtown",
    lat: 34.4218,
    lng: -119.7015,
    mapUrl: "https://www.google.com/maps/search/?api=1&query=Panino+834+Santa+Barbara+St%2C+Santa+Barbara%2C+CA+93101",
    appleMapsUrl: null,
    website: "https://www.paninorestaurants.com",
    phone: "805-963-3700",
    instagram: null,
    menuItems: [],
  },
  {
    name: "Poke House",
    address: "811 State St, Ste D, Santa Barbara, CA 93101",
    area: "Downtown",
    lat: 34.4196,
    lng: -119.6986,
    mapUrl: "https://www.google.com/maps/search/?api=1&query=Poke+House+811+State+St%2C+Ste+D%2C+Santa+Barbara%2C+CA+93101",
    appleMapsUrl: null,
    website: "https://www.poke.house",
    phone: "805-869-2722",
    instagram: "poke.house",
    menuItems: [],
  },
  {
    name: "'Que by Whiskey 'N Rye",
    address: "38 W Victoria St, Ste 108, Santa Barbara, CA 93101",
    area: "Downtown",
    lat: 34.4239,
    lng: -119.7038,
    mapUrl: "https://www.google.com/maps/search/?api=1&query=%27Que+by+Whiskey+%27N+Rye+38+W+Victoria+St%2C+Ste+108%2C+Santa+Barbara%2C+CA+93101",
    appleMapsUrl: null,
    website: "https://www.quesmokeshack.com",
    phone: "805-869-2193",
    instagram: "quesmokeshack",
    menuItems: [],
  },
  {
    name: "Rinkside Cafe",
    address: "6985 Santa Felicia Dr, Goleta, CA 93117",
    area: "Goleta",
    lat: 34.4358,
    lng: -119.8676,
    mapUrl: "https://www.google.com/maps/search/?api=1&query=Rinkside+Cafe+6985+Santa+Felicia+Dr%2C+Goleta%2C+CA+93117",
    appleMapsUrl: null,
    website: "https://www.iceinparadise.org/rinkside-cafe",
    phone: null,
    instagram: "rinksidecafe",
    menuItems: [],
  },
  {
    name: "Santa Barbara Fish Market",
    address: "7127 Hollister Ave, Ste 18, Goleta, CA 93117",
    area: "Goleta",
    lat: 34.428633,
    lng: -119.876655,
    mapUrl: "https://www.google.com/maps/search/?api=1&query=Santa+Barbara+Fish+Market+7127+Hollister+Ave%2C+Goleta%2C+CA+93117",
    appleMapsUrl: null,
    website: "https://www.sbfish.com",
    phone: "805-965-9564",
    instagram: "sbfishmarket",
    menuItems: [],
  },
  {
    name: "Santa Barbara Pizza House",
    address: "515 State St, Santa Barbara, CA 93101",
    area: "Downtown",
    lat: 34.4174,
    lng: -119.696,
    mapUrl: "https://www.google.com/maps/search/?api=1&query=Santa+Barbara+Pizza+House+515+State+St%2C+Santa+Barbara%2C+CA+93101",
    appleMapsUrl: null,
    website: "https://www.sbpizzahouse.com",
    phone: "805-637-7721",
    instagram: null,
    menuItems: [],
  },
  {
    name: "Shalhoob's Funk Zone Patio",
    address: "220 Gray Ave, Santa Barbara, CA 93101",
    otherLocations: [
      "5112 Hollister Ave, Goleta",
    ],
    area: "Funk Zone",
    lat: 34.4143,
    lng: -119.6897,
    mapUrl: "https://www.google.com/maps/search/?api=1&query=Shalhoob%27s+Funk+Zone+Patio+220+Gray+Ave%2C+Santa+Barbara%2C+CA+93101",
    appleMapsUrl: null,
    website: "https://shalhoob.com",
    phone: "805-256-7353",
    instagram: "shalhoobmeatco",
    menuItems: [],
  },
  {
    name: "South Coast Deli",
    address: "10 E Carrillo St, Santa Barbara, CA 93101",
    otherLocations: [
      "185 S Patterson St, Santa Barbara",
      "3534 State St, Santa Barbara",
      "205 Santa Barbara St, Santa Barbara",
    ],
    area: "Downtown",
    lat: 34.4208,
    lng: -119.7016,
    mapUrl: "https://www.google.com/maps/search/?api=1&query=South+Coast+Deli+10+E+Carrillo+St%2C+Santa+Barbara%2C+CA+93101",
    appleMapsUrl: null,
    website: "https://southcoastdeli.com/",
    phone: "805-845-4600",
    instagram: null,
    menuItems: [],
  },
  {
    name: "The Blue Owl",
    address: "5 W Canon Perdido St, Santa Barbara, CA 93101",
    area: "Downtown",
    lat: 34.4189,
    lng: -119.6985,
    mapUrl: "https://www.google.com/maps/search/?api=1&query=The+Blue+Owl+5+W+Canon+Perdido+St%2C+Santa+Barbara%2C+CA+93101",
    appleMapsUrl: null,
    website: "https://theblueowlsb.com/",
    phone: "805-705-0991",
    instagram: "blueowlsb",
    menuItems: [],
  },
  {
    name: "The Natural Cafe",
    address: "361 Hitchcock Way, Santa Barbara, CA 93105",
    otherLocations: [
      "6990 Marketplace Dr, Goleta",
    ],
    area: "Upper State",
    lat: 34.4378,
    lng: -119.7466,
    mapUrl: "https://www.google.com/maps/search/?api=1&query=The+Natural+Cafe+361+Hitchcock+Way%2C+Santa+Barbara%2C+CA+93105",
    appleMapsUrl: null,
    website: "https://thenaturalcafe.com/",
    phone: "805-563-1163",
    instagram: null,
    menuItems: [],
  },
  {
    name: "The Patio Cafe",
    address: "3007 De La Vina St, Santa Barbara, CA 93105",
    area: "Upper State",
    lat: 34.4348,
    lng: -119.7268,
    mapUrl: "https://www.google.com/maps/search/?api=1&query=The+Patio+Cafe+3007+De+La+Vina+St%2C+Santa+Barbara%2C+CA+93105",
    appleMapsUrl: null,
    website: "https://www.thepatiocafesb.com/",
    phone: "805-687-3663",
    instagram: null,
    menuItems: [],
  },
  {
    name: "Valentino's Take N' Bake Pizza",
    address: "4421 Hollister Ave, Santa Barbara, CA 93110",
    area: "Noleta",
    lat: 34.4366,
    lng: -119.7795,
    mapUrl: "https://www.google.com/maps/search/?api=1&query=Valentino%27s+Take+N%27+Bake+Pizza+4421+Hollister+Ave%2C+Santa+Barbara%2C+CA+93110",
    appleMapsUrl: null,
    website: null,
    phone: "805-967-7338",
    instagram: "valentinos_sb",
    menuItems: [],
  },
  {
    name: "Validation Ale",
    address: "102 E Yanonali St, Santa Barbara, CA 93101",
    otherLocations: [
      "2840 De La Vina St, Santa Barbara",
    ],
    area: "Funk Zone",
    lat: 34.4138,
    lng: -119.6889,
    mapUrl: "https://www.google.com/maps/search/?api=1&query=Validation+Ale+102+E+Yanonali+St%2C+Santa+Barbara%2C+CA+93101",
    appleMapsUrl: null,
    website: "https://www.validationale.com/",
    phone: "805-500-3111",
    instagram: null,
    menuItems: [],
  },
  {
    name: "Yellow Belly",
    address: "2611 De La Vina St, Santa Barbara, CA 93105",
    area: "Downtown",
    lat: 34.4317,
    lng: -119.724,
    mapUrl: "https://www.google.com/maps/search/?api=1&query=Yellow+Belly+2611+De+La+Vina+St%2C+Santa+Barbara%2C+CA+93105",
    appleMapsUrl: null,
    website: "https://www.yellowbellytap.com/",
    phone: "805-770-5694",
    instagram: null,
    menuItems: [],
  },
];
